---

- hosts: node1
  become: yes
  tasks:
   - name: Installing DB 
     ansible.builtin.file:
       path: /root/db.conf
       state: touch
       mode: '0644'
- hosts: node2
  become: yes
  tasks:
   - name: Installing App
     ansible.builtin.file:
       path: /root/App.conf
       state: touch
       mode: '0644'
